/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.PanelPrinter;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Vilma Gaming
 */
public class individualprinting extends javax.swing.JFrame {

    /**
     * Creates new form individualprinting
     */
    public individualprinting() {
        initComponents();
    }
    
    public  String destination = "";
    File selectedfile;
    public String oldpath;
    public String path;
    public String image;
    public String ImageIcon;
    public String ResizeImage;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        page = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        img = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        st = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        cn = new javax.swing.JLabel();
        an = new javax.swing.JLabel();
        pn = new javax.swing.JLabel();
        qn = new javax.swing.JLabel();
        ap = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        n = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        g1 = new javax.swing.JLabel();
        g2 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        da = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 60, 50));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRINTING");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 610, 50);

        page.setBackground(new java.awt.Color(0, 204, 204));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, 550, -1));

        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setText("No Image Found");
        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        page.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 260, 280));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BAKERY SYSTEM");
        page.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 530, 50));

        st.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        page.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 180, 30));

        id.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        page.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 180, 30));

        cn.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        page.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, 30));

        an.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        page.add(an, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, 30));

        pn.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        page.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 180, 30));

        qn.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        page.add(qn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 180, 30));

        ap.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        page.add(ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 180, 30));

        p1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        p1.setText("ID:");
        page.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 30));

        p.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        p.setText("Customer's Name:");
        page.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 30));

        n.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        n.setText("Product's Name:");
        page.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 30));

        g.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        g.setText("Quantity:");
        page.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, 30));

        g1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        g1.setText("Amount Paid:");
        page.add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, 30));

        g2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        g2.setText("Date Ordered:");
        page.add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 120, 30));

        status.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        status.setText("Status:");
        page.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 120, 30));

        da.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        page.add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 180, 30));

        jPanel1.add(page);
        page.setBounds(30, 100, 550, 440);

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(500, 60, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       Orders rr = new Orders();
        rr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JPanel myPanel = new JPanel();
        PanelPrinter print = new PanelPrinter(page);
        print.printPanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(individualprinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(individualprinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(individualprinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(individualprinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new individualprinting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel an;
    public javax.swing.JLabel ap;
    public javax.swing.JLabel cn;
    public javax.swing.JLabel da;
    private javax.swing.JLabel g;
    private javax.swing.JLabel g1;
    private javax.swing.JLabel g2;
    public javax.swing.JLabel id;
    public javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel n;
    private javax.swing.JLabel p;
    private javax.swing.JLabel p1;
    private javax.swing.JPanel page;
    public javax.swing.JLabel pn;
    public javax.swing.JLabel qn;
    public javax.swing.JLabel st;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables

    private int getHeightFromWidth(String ImagePath, int width) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    
    }

